### ISSUE TITLE
Optional Features

### ISSUE THREAD

**Issue by Flofus** [Settlers4Modding/CommunityPatchLauncher#84] opened 2021-01-30 21:01 UTC
- Autosave by changing folders
- auto minimize  after starting SIV (option Marker)

**Comment by XanatosX** [comment] 2021-01-30 21:28
Not surw if we should auto save the folder changes this would collide with the save button in my opinion

**Comment by XanatosX** [comment] 2021-01-30 21:29
Adding a minimize function should be a quick addition

**Comment by XanatosX** [comment] 2021-02-04 17:19
Please check this if #109 is merged and you client is up to date.

This should add the minimize on gamestart option.

**Comment by Flofus** [comment] 2021-02-05 16:28
> Please check this if #109 is merged and you client is up to date.
> 
> This should add the minimize on gamestart option.

Checked but not working and the Setting were not saved

**Comment by XanatosX** [comment] 2021-02-08 16:51
I can't reproduce the behavior, did you find any steps to reproduce. I did try it with a clean setting file I tried it with a already written setting file and could not reproduce.

Did you find any steps to reproduce?

**Comment by Flofus** [comment] 2021-02-08 16:53
I think it was a bug, i cannot reproduce it now

**Comment by XanatosX** [comment] 2021-02-08 17:03
Hmm okay I will watch this issue and if do find it again try to solve it. For now I would call it fixed :)

If you are happy with the changes please close the issue

**Closed** 2021-02-08 17:04 UTC
Labels: backend, frontend, status > completed, type > enhancement
